### Notebook to check WRMSSE score

Note: This script is used to run submission score on local machine

In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 5GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

In [2]:
from typing import Union
from tqdm.notebook import tqdm
import gc; gc.enable()

## read in all answers

In [3]:
### train: days [1; 1913] or [2011-01-29; 2016-04-24]

### test week_1: days [1914 : 1920] or [2016-04-25 : 2016-05-01]
# df = df.loc[(df.d<=1913)| ((df.d>=1914)&(df.d<=1920))]
#df.loc[(df.d<=1913)| ((df.d>=1914)&(df.d<=1920))][:'2016-04-24'] # train split
#df.loc[(df.d<=1913)| ((df.d>=1914)&(df.d<=1920))]['2016-04-25':] # test split


### test week_2: days [1921 : 1927] or [2016-05-02 : 2016-05-08]
# df = df.loc[(df.d<=1913)| ((df.d>=1921)&(df.d<=1927))]
# #df.loc[(df.d<=1913)| ((df.d>=1921)&(df.d<=1927))][:'2016-04-24'] # train split
# #df.loc[(df.d<=1913)| ((df.d>=1921)&(df.d<=1927))]['2016-04-25':] # test split


### test week_3: days [1928 : 1934] or [2016-05-09 : 2016-05-15]
# df = df.loc[(df.d<=1913)| ((df.d>=1928)&(df.d<=1934))]
# #df.loc[(df.d<=1913)| ((df.d>=1928)&(df.d<=1934))][:'2016-04-24'] # train split
# #df.loc[(df.d<=1913)| ((df.d>=1928)&(df.d<=1934))]['2016-04-25':] # test split

### test week_4: days [1935 : 1941] or [2016-05-16 : 2016-05-22]
# df = df.loc[(df.d<=1913)| ((df.d>=1935)&(df.d<=1941))]
# #df.loc[(df.d<=1913)| ((df.d>=1935)&(df.d<=1941))][:'2016-04-24'] # train split
# #df.loc[(df.d<=1913)| ((df.d>=1935)&(df.d<=1941))]['2016-04-25':] # test split

In [4]:
# tmp=pd.DataFrame()

# weeks= range(1,4+1)
# data_splits = range(1,7+1)

# for split in data_splits:
#     for week in weeks:
#         df = pd.read_pickle(f'../input/1-revenue-all-df/df_{split}.pkl')
#         df_pred = pd.read_pickle(f'../input/2-revenue-wk-1-df-1/wk_{week}_pred_1.pkl')
        
#         if week == 1:
#             df_new = df.loc[(df.d>=1914)&(df.d<=1920)][['id','d']]
#             df_new.reset_index(inplace=True)
#             df_new = pd.concat([df_new,df_pred],axis=1)

In [5]:
combined_df = pd.DataFrame()

# data_splits = range(1,7+1)
data_splits = range(1,5+1)


for split in data_splits:
    df = pd.read_pickle(f'../input/4-combined-df/df_{split}.pkl')
    df.set_index('date',inplace=True)
    df.sort_values(by='date',inplace=True)

    df = df['2016-04-25':][['id','d']]
#     df.reset_index(inplace=True)
    combined_df = pd.concat([combined_df, df])
combined_df.reset_index(inplace=True)
del df
gc.collect()

0

In [6]:
combined_df

             date                               id     d
0      2016-04-25      FOODS_3_718_CA_1_evaluation  1914
1      2016-04-25      FOODS_3_575_CA_2_evaluation  1914
2      2016-04-25      FOODS_3_127_CA_1_evaluation  1914
3      2016-04-25      FOODS_3_079_CA_1_evaluation  1914
4      2016-04-25      FOODS_3_565_CA_2_evaluation  1914
...           ...                              ...   ...
853715 2016-05-22    HOBBIES_2_113_WI_3_evaluation  1941
853716 2016-05-22    HOBBIES_2_112_WI_3_evaluation  1941
853717 2016-05-22  HOUSEHOLD_2_163_TX_3_evaluation  1941
853718 2016-05-22    HOBBIES_2_119_WI_3_evaluation  1941
853719 2016-05-22      FOODS_3_827_WI_3_evaluation  1941

[853720 rows x 3 columns]

In [7]:
# combined_df.id.nunique()

In [8]:
# combined_df_all_pred =pd.DataFrame()

# weeks= range(1,4+1)
# # data_splits = range(1,7+1)
# data_splits = range(1,5+1)

# for split in data_splits:
#     each_df_all_weeks = pd.DataFrame() 
    
#     for week in weeks:
#         df_pred = pd.read_pickle(f'../input/4-combined-df-{split}-week-{week}/wk_{week}_pred_{split}.pkl')
#         each_df_all_weeks = pd.concat([each_df_all_weeks, df_pred])
    
#     combined_df_all_pred = pd.concat([combined_df_all_pred, each_df_all_weeks])

# del df_pred
# del each_df_all_weeks

# combined_df_all_pred.rename(columns={0: "pred"},inplace=True)
# combined_df_all_pred.reset_index(inplace=True)
# del combined_df_all_pred['index']

In [9]:
combined_df_all_pred =pd.DataFrame()

data_splits = range(1,5+1)

for split in data_splits:
    df_pred = pd.read_pickle(f'../input/9-full-month-df-{split}-label-enc/full_month_pred_{split}.pkl')
    
    combined_df_all_pred = pd.concat([combined_df_all_pred, df_pred])

del df_pred

combined_df_all_pred.rename(columns={0: "pred"},inplace=True)
combined_df_all_pred.reset_index(inplace=True)
del combined_df_all_pred['index']

In [10]:
combined_df_all_pred

            pred
0       1.952004
1       0.644115
2       4.586864
3       0.166101
4       2.518305
...          ...
853715  0.097836
853716  0.249376
853717  0.142131
853718  0.101912
853719  0.845570

[853720 rows x 1 columns]

In [11]:
combined_df.shape

(853720, 3)

In [12]:
df = pd.concat([combined_df,combined_df_all_pred],axis=1)

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 853720 entries, 0 to 853719
Data columns (total 4 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   date    853720 non-null  datetime64[ns]
 1   id      853720 non-null  category
 2   d       853720 non-null  int16
 3   pred    853720 non-null  float32
dtypes: category(1), datetime64[ns](1), float32(1), int16(1)
memory usage: 14.5 MB

In [14]:
df = df.pivot(index='id', columns='d', values='pred')
df.reset_index(inplace=True)
df.columns.name=None

df.rename(columns = {
    1914:"F1", 1915:"F2", 1916:"F3", 1917:"F4", 1918:"F5", 1919:"F6", 1920:"F7",
    1921:"F8", 1922:"F9", 1923:"F10", 1924:"F11", 1925:"F12", 1926:"F13", 1927:"F14",
    1928:"F15", 1929:"F16", 1930:"F17", 1931:"F18", 1932:"F19", 1933:"F20", 1934:"F21",
    1935:"F22", 1936:"F23", 1937:"F24", 1938:"F25", 1939:"F26", 1940:"F27", 1941:"F28"
},inplace=True)

df2 = df.copy()

df["id"] = df["id"].str.replace("evaluation$","validation")

df2[[c for c in df2.columns.tolist() if c != 'id']]=0

subm = pd.concat([df, df2], axis=0, sort=False)
subm.reset_index(inplace=True)
del subm['index']

In [15]:
subm

,id,F1,F2,F3,F4,F5,F6,F7,F8,F9,...,F19,F20,F21,F22,F23,F24,F25,F26,F27,F28
0,FOODS_1_001_CA_1_validation,1.129108,0.991194,0.981775,0.851283,1.232610,1.274570,0.915326,1.400763,1.214867,...,1.088345,1.181482,1.109957,1.621987,1.400183,1.407075,0.728638,1.150045,0.996468,1.013246
1,FOODS_1_001_CA_2_validation,1.059303,0.635132,0.571182,0.618105,0.564431,0.990327,0.482427,0.981029,0.700068,...,0.509800,0.567648,2.487012,2.066694,1.401941,0.948423,1.035479,1.256904,1.746528,1.904324
2,FOODS_1_001_CA_3_validation,1.803183,1.262216,1.018108,0.894469,1.149433,1.313589,1.077446,1.009328,0.737625,...,0.789024,1.672721,2.268938,2.119604,1.655497,1.364411,0.900770,0.822732,2.010181,1.241529
3,FOODS_1_001_CA_4_validation,0.955066,0.584009,0.530746,0.490641,0.612996,0.388293,0.338078,0.847343,0.419779,...,0.302219,0.372712,0.239430,0.680762,0.428708,0.484979,0.296204,0.340076,0.497729,0.540623
4,FOODS_1_001_TX_1_validation,0.470691,0.384899,0.431144,0.513716,0.376714,0.344220,0.908792,0.389704,0.416308,...,0.346919,0.279478,0.385411,0.270895,0.225015,0.265510,0.150962,0.372843,0.150993,0.147038
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
60975,HOUSEHOLD_2_516_TX_2_evaluation,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
60976,HOUSEHOLD_2_516_TX_3_evaluation,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
60977,HOUSEHOLD_2_516_WI_1_evaluation,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
60978,HOUSEHOLD_2_516_WI_2_evaluation,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
60979,HOUSEHOLD_2_516_WI_3_evaluation,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000

In [16]:
subm.columns

Index(['id', 'F1', 'F2', 'F3', 'F4', 'F5', 'F6', 'F7', 'F8', 'F9', 'F10',
       'F11', 'F12', 'F13', 'F14', 'F15', 'F16', 'F17', 'F18', 'F19', 'F20',
       'F21', 'F22', 'F23', 'F24', 'F25', 'F26', 'F27', 'F28'],
      dtype='object')

In [17]:
# 'HOBBIES_1_147_CA_1_evaluation'[:-10]+'validation'

In [18]:
sample = pd.read_csv('../input/m5-forecasting-accuracy/sample_submission.csv')
sample

,id,F1,F2,F3,F4,F5,F6,F7,F8,F9,...,F19,F20,F21,F22,F23,F24,F25,F26,F27,F28
0,HOBBIES_1_001_CA_1_validation,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,HOBBIES_1_002_CA_1_validation,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,HOBBIES_1_003_CA_1_validation,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,HOBBIES_1_004_CA_1_validation,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,HOBBIES_1_005_CA_1_validation,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
60975,FOODS_3_823_WI_3_evaluation,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
60976,FOODS_3_824_WI_3_evaluation,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
60977,FOODS_3_825_WI_3_evaluation,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
60978,FOODS_3_826_WI_3_evaluation,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
60979,FOODS_3_827_WI_3_evaluation,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [19]:
# len(sample.index)

In [20]:
# sum((sample.index == subm.index).tolist())

In [21]:
subm = sample[['id']].merge(subm, on='id', how='left')

In [22]:
# sample.columns

In [23]:
subm

,id,F1,F2,F3,F4,F5,F6,F7,F8,F9,...,F19,F20,F21,F22,F23,F24,F25,F26,F27,F28
0,HOBBIES_1_001_CA_1_validation,0.977432,1.104784,0.811051,0.767400,1.066951,0.618981,0.913799,0.671263,1.198248,...,1.071529,1.346178,1.339352,0.888382,1.079321,1.014747,1.288510,1.087393,1.051955,0.999671
1,HOBBIES_1_002_CA_1_validation,0.564918,0.382404,0.341499,0.506219,0.357674,0.426823,0.422992,0.406487,0.260534,...,0.257760,0.281104,0.273708,0.268545,0.189484,0.322984,0.375643,0.313361,0.294131,0.276937
2,HOBBIES_1_003_CA_1_validation,0.397784,0.406814,0.272703,0.341965,0.440046,0.835259,0.495789,0.443095,0.460046,...,0.888291,0.753822,0.744954,0.618653,0.638226,0.736189,0.718396,0.741644,0.829397,0.880312
3,HOBBIES_1_004_CA_1_validation,2.300084,1.416003,1.261988,1.403253,1.848392,2.193557,2.220382,1.825767,1.407694,...,1.926821,2.063901,2.378833,2.313170,1.915570,1.526066,1.309305,1.621925,3.161928,3.238765
4,HOBBIES_1_005_CA_1_validation,1.330223,1.166545,1.377252,1.469506,1.509465,1.075743,1.272607,1.472999,1.439863,...,1.136151,1.221709,1.354367,0.973341,0.974638,1.186054,1.377540,1.148692,1.276335,1.713395
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
60975,FOODS_3_823_WI_3_evaluation,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
60976,FOODS_3_824_WI_3_evaluation,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
60977,FOODS_3_825_WI_3_evaluation,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
60978,FOODS_3_826_WI_3_evaluation,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
60979,FOODS_3_827_WI_3_evaluation,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000

In [24]:
subm.to_csv('subm_3.csv',index=False)

In [25]:
## evaluation metric
## from https://www.kaggle.com/c/m5-forecasting-accuracy/discussion/133834 and edited to get scores at all levels
class WRMSSEEvaluator(object):

    def __init__(self, train_df: pd.DataFrame, valid_df: pd.DataFrame, calendar: pd.DataFrame, prices: pd.DataFrame):
        train_y = train_df.loc[:, train_df.columns.str.startswith('d_')]
        train_target_columns = train_y.columns.tolist()
        weight_columns = train_y.iloc[:, -28:].columns.tolist()

        train_df['all_id'] = 0  # for lv1 aggregation

        id_columns = train_df.loc[:, ~train_df.columns.str.startswith('d_')].columns.tolist()
        valid_target_columns = valid_df.loc[:, valid_df.columns.str.startswith('d_')].columns.tolist()

        if not all([c in valid_df.columns for c in id_columns]):
            valid_df = pd.concat([train_df[id_columns], valid_df], axis=1, sort=False)

        self.train_df = train_df
        self.valid_df = valid_df
        self.calendar = calendar
        self.prices = prices

        self.weight_columns = weight_columns
        self.id_columns = id_columns
        self.valid_target_columns = valid_target_columns

        weight_df = self.get_weight_df()

        self.group_ids = (
            'all_id',
            'cat_id',
            'state_id',
            'dept_id',
            'store_id',
            'item_id',
            ['state_id', 'cat_id'],
            ['state_id', 'dept_id'],
            ['store_id', 'cat_id'],
            ['store_id', 'dept_id'],
            ['item_id', 'state_id'],
            ['item_id', 'store_id']
        )

        for i, group_id in enumerate(tqdm(self.group_ids)):
            train_y = train_df.groupby(group_id)[train_target_columns].sum()
            scale = []
            for _, row in train_y.iterrows():
                series = row.values[np.argmax(row.values != 0):]
                scale.append(((series[1:] - series[:-1]) ** 2).mean())
            setattr(self, f'lv{i + 1}_scale', np.array(scale))
            setattr(self, f'lv{i + 1}_train_df', train_y)
            setattr(self, f'lv{i + 1}_valid_df', valid_df.groupby(group_id)[valid_target_columns].sum())

            lv_weight = weight_df.groupby(group_id)[weight_columns].sum().sum(axis=1)
            setattr(self, f'lv{i + 1}_weight', lv_weight / lv_weight.sum())

    def get_weight_df(self) -> pd.DataFrame:
        day_to_week = self.calendar.set_index('d')['wm_yr_wk'].to_dict()
        weight_df = self.train_df[['item_id', 'store_id'] + self.weight_columns].set_index(['item_id', 'store_id'])
        weight_df = weight_df.stack().reset_index().rename(columns={'level_2': 'd', 0: 'value'})
        weight_df['wm_yr_wk'] = weight_df['d'].map(day_to_week)

        weight_df = weight_df.merge(self.prices, how='left', on=['item_id', 'store_id', 'wm_yr_wk'])
        weight_df['value'] = weight_df['value'] * weight_df['sell_price']
        weight_df = weight_df.set_index(['item_id', 'store_id', 'd']).unstack(level=2)['value']
        weight_df = weight_df.loc[zip(self.train_df.item_id, self.train_df.store_id), :].reset_index(drop=True)
        weight_df = pd.concat([self.train_df[self.id_columns], weight_df], axis=1, sort=False)
        return weight_df

    def rmsse(self, valid_preds: pd.DataFrame, lv: int) -> pd.Series:
        valid_y = getattr(self, f'lv{lv}_valid_df')
        score = ((valid_y - valid_preds) ** 2).mean(axis=1)
        scale = getattr(self, f'lv{lv}_scale')
        return (score / scale).map(np.sqrt)

    def score(self, valid_preds: Union[pd.DataFrame, np.ndarray]) -> float:
        assert self.valid_df[self.valid_target_columns].shape == valid_preds.shape

        if isinstance(valid_preds, np.ndarray):
            valid_preds = pd.DataFrame(valid_preds, columns=self.valid_target_columns)

        valid_preds = pd.concat([self.valid_df[self.id_columns], valid_preds], axis=1, sort=False)

        group_ids = []
        all_scores = []
        for i, group_id in enumerate(self.group_ids):
            lv_scores = self.rmsse(valid_preds.groupby(group_id)[self.valid_target_columns].sum(), i + 1)
            weight = getattr(self, f'lv{i + 1}_weight')
            lv_scores = pd.concat([weight, lv_scores], axis=1, sort=False).prod(axis=1)
            group_ids.append(group_id)
            all_scores.append(lv_scores.sum())

        return group_ids, all_scores

In [26]:
## new train data
df_train_full = pd.read_csv('../input/m5-forecasting-accuracy/sales_train_evaluation.csv')
df_train_full.iloc[:, -28:].head()

,d_1914,d_1915,d_1916,d_1917,d_1918,d_1919,d_1920,d_1921,d_1922,d_1923,...,d_1932,d_1933,d_1934,d_1935,d_1936,d_1937,d_1938,d_1939,d_1940,d_1941
0,0,0,0,2,0,3,5,0,0,1,...,2,4,0,0,0,0,3,3,0,1
1,0,1,0,0,0,0,0,0,0,1,...,0,1,2,1,1,0,0,0,0,0
2,0,0,1,1,0,2,1,0,0,0,...,1,0,2,0,0,0,2,3,0,1
3,0,0,1,2,4,1,6,4,0,0,...,1,1,0,4,0,1,3,0,2,6
4,1,0,2,3,1,0,3,2,3,1,...,0,0,0,2,1,0,0,2,1,0

In [27]:
## reading data
df_calendar = pd.read_csv('../input/m5-forecasting-accuracy/calendar.csv')
df_prices = pd.read_csv('../input/m5-forecasting-accuracy/sell_prices.csv')
df_sample_submission = pd.read_csv('../input/m5-forecasting-accuracy/sample_submission.csv')
df_sample_submission["order"] = range(df_sample_submission.shape[0])

df_train = df_train_full.iloc[:, :-28]
df_valid = df_train_full.iloc[:, -28:]

evaluator = WRMSSEEvaluator(df_train, df_valid, df_calendar, df_prices)

HBox(children=(FloatProgress(value=0.0, max=12.0), HTML(value='')))

In [28]:
preds_valid = subm.copy() #pd.read_csv("back_up/submission.csv") #np.round(pd.read_csv("back_up/submission.csv"))#
preds_valid = preds_valid[preds_valid.id.str.contains("validation")]
preds_valid = preds_valid.merge(df_sample_submission[["id", "order"]], on = "id").sort_values("order").drop(["id", "order"], axis = 1).reset_index(drop = True)
preds_valid.rename(columns = {
    "F1": "d_1914", "F2": "d_1915", "F3": "d_1916", "F4": "d_1917", "F5": "d_1918", "F6": "d_1919", "F7": "d_1920",
    "F8": "d_1921", "F9": "d_1922", "F10": "d_1923", "F11": "d_1924", "F12": "d_1925", "F13": "d_1926", "F14": "d_1927",
    "F15": "d_1928", "F16": "d_1929", "F17": "d_1930", "F18": "d_1931", "F19": "d_1932", "F20": "d_1933", "F21": "d_1934",
    "F22": "d_1935", "F23": "d_1936", "F24": "d_1937", "F25": "d_1938", "F26": "d_1939", "F27": "d_1940", "F28": "d_1941"
}, inplace = True)

groups, scores = evaluator.score(preds_valid)

score_public_lb = np.mean(scores)
#score_public_rank = get_lb_rank(score_public_lb)

for i in range(len(groups)):
    print(f"Score for group {groups[i]}: {round(scores[i], 5)}")

print(f"\nPublic LB Score: {round(score_public_lb, 5)}")
#print(f"Public LB Rank: {score_public_rank}")

Score for group all_id: 0.78564
Score for group cat_id: 0.86308
Score for group state_id: 0.79314
Score for group dept_id: 0.92542
Score for group store_id: 0.81597
Score for group item_id: 0.92591
Score for group ['state_id', 'cat_id']: 0.86435
Score for group ['state_id', 'dept_id']: 0.91553
Score for group ['store_id', 'cat_id']: 0.87772
Score for group ['store_id', 'dept_id']: 0.91429
Score for group ['item_id', 'state_id']: 0.8954
Score for group ['item_id', 'store_id']: 0.87112

Public LB Score: 0.87063